-- EDA Database Exploration

-- Explore all objects in the Database
select * from INFORMATION_SCHEMA.TABLES;

-- Explore all columns in the Database
select * from INFORMATION_SCHEMA.COLUMNS
where TABLE_NAME = 'dim_customers'

-- EDA Dimensions Exploration

-- Explore all countries our customers come from
select distinct country
from gold.dim_customers

-- Explore all categories "the major divisions"
select distinct category, subcategory, product_name from gold.dim_products

-- EDA Date Exploration

-- Find the date of the first and last order
-- How many years of sales are available
select min(order_date) as first_order_date,
	   max(order_date) as last_order_date,
	   DATEDIFF(YEAR, min(order_date), max(order_date)) as order_range
from gold.fact_sales

-- Find youngest and oldest customer 
select 
	 min(birth_date) as oldest_birthdate,
	 datediff(year, min(birth_date), getdate()) as oldest_customer,
	 max(birth_date) as youngest_birthdate,
	 datediff(year, max(birth_date), getdate()) as youngest_customer
from gold.dim_customers

-- EDA Measures Exploration
 
 -- Generate a report that shows all key metrics of the business
select 'Total Sales' as measure_name, sum(sales_amount) as measure_value from gold.fact_sales
union all 
select 'Total Quantity' as measure_name, sum(quantity) from gold.fact_sales
union all
select 'Average Selling Price' as measure_name, AVG(price) from gold.fact_sales
union all
select 'Total Number of Orders' as measure_name, count(distinct(order_number)) from gold.fact_sales
union all
select 'Total Number of Products' as measure_name, count(product_key) from gold.dim_products
union all
select 'Total Number of Customers' as measure_name, count(customer_key) from gold.dim_customers
union all
select 'Customers Orders' as measure_name, count(distinct customer_key) from gold.fact_sales

-- EDA Magnitude Analysis

-- Find total customers by countries
select 
	Count(customer_id) as total_customers, 
	country 
from gold.dim_customers 
group by country
order by total_customers desc;

-- Find total customers by gender
select 
	 count(customer_id) as total_customers, 
	 gender
from gold.dim_customers
group by gender
order by total_customers desc;

-- Find total products by category
select 
	 count(product_key) as total_products, 
	 category
from gold.dim_products
group by category
order by total_products desc;

-- What is the avergae costs in each category
select 
	 avg(cost) as average_cost, 
	 category
from gold.dim_products
group by category
order by average_cost desc;

-- What is the total revenue generated for each category
select 
	 sum(sales_amount) as total_sales, 
	 category
from gold.fact_sales fc
join 
	 gold.dim_products dp on fc.product_key = dp.product_key
group by category
order by total_sales;

-- Find total revenue generated by each customer
select 
	dc.customer_key, 
	concat(dc.first_name, ' ', dc.last_name) as customer_name, 
	sum(sales_amount) as total_sales
from gold.dim_customers dc
join gold.fact_sales fs
on 
	 dc.customer_key = fs.customer_key
group by dc.customer_key, concat(dc.first_name,' ', dc.last_name)
order by total_sales desc;

-- What is the distribution of sold items across countries?
select 
	dc.country, 
	count(quantity) as total_quantity, 
	concat(round(sum(quantity)*100/sum(sum(fs.quantity)) over(),2), '%') as contribution
from gold.fact_sales fs
join gold.dim_customers dc
ON fs.customer_key = dc.customer_key
group by country
order by count(quantity) desc

-- EDA Ranking Analysis

-- Which 5 products generate the highest revenue?
select top 5 
		subcategory, 
		sum(fs.sales_amount) as total_revenue 
from gold.dim_products dp 
join gold.fact_sales fs 
on dp.product_key = fs.product_key 
group by subcategory
order by sum(sales_amount) desc;

-- Which 5 products generate the least revenue?
select top 5 
		subcategory, 
		sum(fs.sales_amount) as total_revenue 
from gold.dim_products dp 
join gold.fact_sales fs 
on dp.product_key = fs.product_key 
group by subcategory
order by sum(sales_amount);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
-- Find top 10 customers who have generated the highest revenue
select TOP 10
	dc.customer_key,
	concat(first_name, ' ', last_name) as customer_name,
	sum(fs.sales_amount) as total_revenue
from gold.dim_customers dc
join gold.fact_sales fs
on 
	dc.customer_key = fs.customer_key
group by dc.customer_key, concat(first_name, ' ', last_name)
order by total_revenue DESC;

-- The 3 customers with the fewest orders placed

select top 3
	dc.customer_key,
	concat(first_name, ' ', last_name) as customer_name,
	count(distinct order_number) as total_orders
from gold.dim_customers dc
join gold.fact_sales fs
on dc.customer_key = fs.customer_key
group by dc.customer_key,
	     concat(first_name, ' ', last_name)
order by total_orders

-- EDA Change-Over-Time Trends

select 
	year(order_date) as order_year,
	month(order_date) as order_month,
	sum(sales_amount) as total_sales,
	count(distinct customer_key) as total_customers
from gold.fact_sales
where order_date is not null
group by year(order_date), month(order_date)
order by year(order_date), month(order_date) 

--EDA Cumulative Analysis
-- Calculate the total sales per month and the running total of sales over time
select
	order_date,
	total_sales,
	sum(total_sales) over(order by order_date) as running_sales,
	avg(avg_price) over(order by order_date) as moving_avg_price
from
(
select 
	datetrunc(month,order_date) as order_date,
	sum(sales_amount) as total_sales,
	avg(price) as avg_price
	from gold.fact_sales
where order_date is not null
group by datetrunc(month,order_date)
) t

-- EDA Performance Analysis
/* Analyze the yearly performance of products by comparing their sales to both the average sales performance 
of the product and the previous year's sales */

with yearly_product_sales as (
select 
	year(s.order_date) as order_year,
	p.product_name,
	sum(s.sales_amount) as current_sales
from gold.fact_sales s
join gold.dim_products p
on s.product_key = p.product_key
where s.order_date is not null
group by year(s.order_date), 
		 p.product_name
)

select 
	order_year,
	product_name,
	current_sales,
	avg(current_sales) over(partition by product_name) as avg_sales,
	current_sales - avg(current_sales) over(partition by product_name) as diff_avg,
	case when current_sales - avg(current_sales) over(partition by product_name) > 0 then 'Above Avg'
		 when current_sales - avg(current_sales) over(partition by product_name) < 0 then 'Below Avg'
		 else 'Avg'
	end as avg_change,
-- Year over Year Analysis
	lag(current_sales) over(partition by product_name order by order_year) as py_sales,
	current_sales - lag(current_sales) over(partition by product_name order by order_year) as diff_py,
	case when current_sales - lag(current_sales) over(partition by product_name order by order_year) > 0 then 'Increase'
		 when current_sales - lag(current_sales) over(partition by product_name order by order_year) < 0 then 'Decrease'
		 else 'No Change'
	end as py_change
from yearly_product_sales
order by product_name, order_year

-- EDA Part to Whole Analysis
-- Which category contribute to overall sales
with category_sales as (
select 
	category, sum(sales_amount) as total_sales
from gold.dim_products dp
join gold.fact_sales fs
on dp.product_key = fs.product_key
group by category)
select
	category, 
	total_sales,
	sum(total_sales) over() as overall_sales,
	concat(round((cast(total_sales as float)/sum(total_sales) over())*100,2), '%') as percentage_of_total
from category_sales
order by total_sales desc;

-- EDA Data Segmentation
/* Segment products into cost ranges and count
how many products fall into each segment*/

with product_segments as (
select
	product_key,
	product_name,
	cost,
	case when cost < 100 then 'Below 100'
		 when cost between 100 and 500 then '100-500'
		 when cost between 500 and 1000 then '500-1000'
		 else 'Above 1000'
end as cost_range
from gold.dim_products)

select 
	cost_range,
	count(product_key) as total_products
from product_segments
group by cost_range
order by total_products desc

/* Group customers into three segements based on their spending behaviour:
  - VIP: Customers with atleast 12 months of history and spending more than $5000.
  - Regular: Customers with atleast 12 months of history but spending $5000 or less.
  - New: Customers with a life span of less than 12 months */

 with customer_spending as (
	select 
		c.customer_key,
		concat(c.first_name, ' ', c.last_name) as customer_name,
		sum(f.sales_amount) as total_spending,
		min(f.order_date) as first_order,
		max(f.order_date) as last_order,
		DATEDIFF(month, min(f.order_date), max(f.order_date)) as lifespan 
	from gold.fact_sales f
	left join gold.dim_customers c
	on f.customer_key = c.customer_key
	group by c.customer_key, concat(c.first_name, ' ' ,c.last_name))
select 
	customer_segment,
	count(customer_key) as total_customers from (
		select
			customer_key,
			concat(lifespan, ' Months ') as lifespan,
			case when lifespan >= 12 and total_spending > 5000 then 'VIP'
				 when lifespan >= 12 and total_spending <= 5000 then 'Regular'
				 else 'New'
			end as customer_segment
		from customer_spending) t
	group by customer_segment
	order by total_customers desc;

